// <auto-generated />
namespace Kheech.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingM2MExplicitRelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingM2MExplicitRelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181554392_AddingM2MExplicitRelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
